apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      k8s-app: api-gateway
  template:
    metadata:
      name: api-gateway
      labels:
        k8s-app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: otaviojulianons/api-gateway:1.0.3
        resources:
          limits:
            memory: "112Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    k8s-app: api-gateway
spec:
  type: LoadBalancer
  selector:
    k8s-app: api-gateway
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 80

#kubectl apply -f api-gateway.yml