apiVersion: v1
kind: Pod
metadata:
  name: consul
  labels:
    k8s-app: consul
spec: 
  containers:
    - name: consul
      image: "consul:latest"
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    k8s-app: consul
spec:
  type: LoadBalancer
  selector:
    k8s-app: consul
  ports:
  - protocol: TCP
    port: 8500
    targetPort: 8500                
