apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    k8s-app: api-gateway
spec:
  type: LoadBalancer
  selector:
    k8s-app: api-gateway
  ports:
  - protocol: TCP
    port: 6005
    targetPort: 80

#kubectl apply -f service-gateway.yml