apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      k8s-app: api-gateway
  template:
    metadata:
      name: api-gateway
      labels:
        k8s-app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: otaviojulianons/api-gateway:1.0.1
        resources:
          limits:
            memory: "112Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: api-customer
  template:
    metadata:
      name: api-customer
      labels:
        k8s-app: api-customer
    spec:
      containers:          
      - name: api-customer
        image: otaviojulianons/api-customer:1.0.1
        resources:
          limits:
            memory: "112Mi"
            cpu: "100m"
        ports:
          - containerPort: 80          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-resizer
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: api-resizer
  template:
    metadata:
      name: api-resizer
      labels:
        k8s-app: api-resizer
    spec:
      containers:          
      - name: api-resizer
        image: otaviojulianons/api-resizer:1.0.1
        resources:
          limits:
            memory: "112Mi"
            cpu: "100m"
        ports:
          - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    k8s-app: api-gateway
spec:
  type: LoadBalancer
  selector:
    k8s-app: api-gateway
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: api-customer
  labels:
    k8s-app: api-customer
spec:
  type: LoadBalancer
  selector:
    k8s-app: api-customer
  ports:
  - protocol: TCP
    port: 5006
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-resizer
  labels:
    k8s-app: api-resizer
spec:
  type: LoadBalancer
  selector:
    k8s-app: api-resizer
  ports:
  - protocol: TCP
    port: 5007
    targetPort: 80               

#kubectl apply -f kube-deploy.yml

