apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: api-customer
  template:
    metadata:
      name: api-customer
      labels:
        k8s-app: api-customer
    spec:
      containers:          
      - name: api-customer
        image: otaviojulianons/api-customer:1.0.3
        resources:
          limits:
            memory: "112Mi"
            cpu: "100m"
        ports:
          - containerPort: 80          
---
apiVersion: v1
kind: Service
metadata:
  name: api-customer
  labels:
    k8s-app: api-customer
spec:
  type: LoadBalancer
  selector:
    k8s-app: api-customer
  ports:
  - protocol: TCP
    port: 5006
    targetPort: 80

#kubectl apply -f api-customer.yml