version: '3'
services:
  api-gateway:
    image: "otaviojulianons/api-gateway:1.0.3"
    ports:
      - "5005:80"
    networks:
      - my_net      
    depends_on:
      - rabbitmq
  api-customer:
    image: "otaviojulianons/api-customer:1.0.3"
    ports:
      - "5006:80"
    networks:
      - my_net  
    depends_on:
      - rabbitmq    
  api-resizer:
    image: "otaviojulianons/api-resizer:1.0.3"
    ports:
      - "5007:80"
    networks:
      - my_net    
    depends_on:
      - rabbitmq        
  api-fileserver:
    image: "otaviojulianons/api-fileserver:1.0.3"
    ports:
      - "5008:80" 
    networks:
      - my_net            
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "25676:25676"
    networks:
      - my_net          
    # docker run -d -p 15672:15672 -p 5672:5672 -p 25676:25676 --name myrabbit rabbitmq:3-management
    # user: guest password: guest
networks:
  my_net:
    driver: bridge  